spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uniapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  messages:
    basename: i18n/messages

resilience4j:
  circuitbreaker:
    instances:
      getAllStudents:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        failure-rate-threshold: 50.0
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 1500
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true

kafka:
  url: localhost:9092